# Generated by Django 4.0.6 on 2022-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment_chk_comments_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('publish_product', 'Can publish product')]},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
